# Generated by Django 4.1.1 on 2022-09-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
