# Generated by Django 4.1.1 on 2022-09-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_application_user_alter_application_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
    ]
