# Generated by Django 4.1.1 on 2022-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_remove_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="notes",
            field=models.TextField(blank=True, default="Add some notes", null=True),
        ),
    ]
