# Generated by Django 4.1.1 on 2022-09-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_application_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
    ]
