# Generated by Django 4.1.1 on 2022-09-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_remove_application_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="date_applied",
        ),
        migrations.RemoveField(
            model_name="application",
            name="location",
        ),
        migrations.RemoveField(
            model_name="application",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="application",
            name="name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
        migrations.RemoveField(
            model_name="application",
            name="title",
        ),
    ]
