# Generated by Django 4.1.1 on 2022-09-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_application_date_applied_application_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
    ]
