# Generated by Django 4.1.1 on 2022-09-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
